### ISSUE TITLE
I'm trying to use this via JitPack

### ISSUE THREAD

**Issue by mirza-suljic** [izohek/warno-deck-utils#1]
Hi,
love your work. I was looking into pulling your repo in as a dependancy for my Armroy and I came across JitPack. The idea is to just paste a GitHub link and get a Maven dependancy in the JitPack repo.
However, when I try to use this repo via JitPack, I get this error:
```
Build starting...
Start: Wed Feb 22 10:57:06 UTC 2023 38c8aa50f98e
Git:
v0.2.3-0-g4154823
commit 4154823330f95861efca0f1069a3aecc52e79f5a
Author: izohek 
Date:   Mon Feb 20 13:07:26 2023 -0800

    0.2.3


Init SDKMan

ERROR:
No build file found. Looking for Gradle/Maven/Sbt/Lein build file in the root of the project
See the documentation at https://docs.jitpack.io
Files: 
LICENSE
README.md
dist
jest.config.js
package-lock.json
package.json
src
tests
tsconfig.json
2023-02-22T10:57:07.081281978Z
Exit code: 1

⚠️ ERROR: No build artifacts found

```

Is this something you'd like to look into?

**Comment by mirza-suljic** [comment]
I cloned your repo and made a local branch with an added pom.xml according to JitPack. I'd push it for you to see if you like.

**Comment by mirza-suljic** [comment]
Another way is this https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry

Which do you prefer?

**Comment by mirza-suljic** [comment]
Or nevermind. Git has submodules. I'm a dumbass.

**Comment by izohek** [comment]
If submodules are working for you, that's probably the preferred way from my point of view.  I'm not super familiar with Maven so while I'd consider a PR if you wanted to do it, I'm not really sure I can commit to maintaining it.  Sub modules offer me the added benefit of not having to support extra build systems.

**Comment by mirza-suljic** [comment]
I agree.
